FROM eclipse-temurin:21 AS builder

RUN apt-get update && apt-get install -y maven

WORKDIR /app

COPY . .

RUN mvn test

RUN mvn clean package -DskipTests

FROM eclipse-temurin:21

WORKDIR /app

COPY --from=builder /app/target/*.jar app.jar

CMD ["java", "-jar", "app.jar"]