name: Secret Demo

on:
  push:

jobs:
  show-secret:
    runs-on: ubuntu-latest
    env:
      ACTIONS_RUNNER_DEBUG: true
      ACTIONS_STEP_DEBUG: true
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Mostrar secret configurado
        run: echo "API_KEY configurado"
